//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class ContactsStampedMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/ContactsStamped";
        public override string RosMessageName => k_RosMessageName;

        public Std.HeaderMsg header;
        public bool[] contacts;

        public ContactsStampedMsg()
        {
            this.header = new Std.HeaderMsg();
            this.contacts = new bool[0];
        }

        public ContactsStampedMsg(Std.HeaderMsg header, bool[] contacts)
        {
            this.header = header;
            this.contacts = contacts;
        }

        public static ContactsStampedMsg Deserialize(MessageDeserializer deserializer) => new ContactsStampedMsg(deserializer);

        private ContactsStampedMsg(MessageDeserializer deserializer)
        {
            this.header = Std.HeaderMsg.Deserialize(deserializer);
            deserializer.Read(out this.contacts, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.header);
            serializer.WriteLength(this.contacts);
            serializer.Write(this.contacts);
        }

        public override string ToString()
        {
            return "ContactsStampedMsg: " +
            "\nheader: " + header.ToString() +
            "\ncontacts: " + System.String.Join(", ", contacts.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
