//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class ContactsMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/Contacts";
        public override string RosMessageName => k_RosMessageName;

        public bool[] contacts;

        public ContactsMsg()
        {
            this.contacts = new bool[0];
        }

        public ContactsMsg(bool[] contacts)
        {
            this.contacts = contacts;
        }

        public static ContactsMsg Deserialize(MessageDeserializer deserializer) => new ContactsMsg(deserializer);

        private ContactsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.contacts, sizeof(bool), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.contacts);
            serializer.Write(this.contacts);
        }

        public override string ToString()
        {
            return "ContactsMsg: " +
            "\ncontacts: " + System.String.Join(", ", contacts.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
