//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class ImuMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/Imu";
        public override string RosMessageName => k_RosMessageName;

        public Geometry.QuaternionMsg orientation;
        public Geometry.Vector3Msg linear_acceleration;
        public Geometry.Vector3Msg angular_velocity;
        public Geometry.Vector3Msg magnetic_field;

        public ImuMsg()
        {
            this.orientation = new Geometry.QuaternionMsg();
            this.linear_acceleration = new Geometry.Vector3Msg();
            this.angular_velocity = new Geometry.Vector3Msg();
            this.magnetic_field = new Geometry.Vector3Msg();
        }

        public ImuMsg(Geometry.QuaternionMsg orientation, Geometry.Vector3Msg linear_acceleration, Geometry.Vector3Msg angular_velocity, Geometry.Vector3Msg magnetic_field)
        {
            this.orientation = orientation;
            this.linear_acceleration = linear_acceleration;
            this.angular_velocity = angular_velocity;
            this.magnetic_field = magnetic_field;
        }

        public static ImuMsg Deserialize(MessageDeserializer deserializer) => new ImuMsg(deserializer);

        private ImuMsg(MessageDeserializer deserializer)
        {
            this.orientation = Geometry.QuaternionMsg.Deserialize(deserializer);
            this.linear_acceleration = Geometry.Vector3Msg.Deserialize(deserializer);
            this.angular_velocity = Geometry.Vector3Msg.Deserialize(deserializer);
            this.magnetic_field = Geometry.Vector3Msg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.orientation);
            serializer.Write(this.linear_acceleration);
            serializer.Write(this.angular_velocity);
            serializer.Write(this.magnetic_field);
        }

        public override string ToString()
        {
            return "ImuMsg: " +
            "\norientation: " + orientation.ToString() +
            "\nlinear_acceleration: " + linear_acceleration.ToString() +
            "\nangular_velocity: " + angular_velocity.ToString() +
            "\nmagnetic_field: " + magnetic_field.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
