//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class JointsMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/Joints";
        public override string RosMessageName => k_RosMessageName;

        public float[] position;

        public JointsMsg()
        {
            this.position = new float[0];
        }

        public JointsMsg(float[] position)
        {
            this.position = position;
        }

        public static JointsMsg Deserialize(MessageDeserializer deserializer) => new JointsMsg(deserializer);

        private JointsMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.position, sizeof(float), deserializer.ReadLength());
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.WriteLength(this.position);
            serializer.Write(this.position);
        }

        public override string ToString()
        {
            return "JointsMsg: " +
            "\nposition: " + System.String.Join(", ", position.ToList());
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
