//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class PIDMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/PID";
        public override string RosMessageName => k_RosMessageName;

        public float p;
        public float d;
        public float i;

        public PIDMsg()
        {
            this.p = 0.0f;
            this.d = 0.0f;
            this.i = 0.0f;
        }

        public PIDMsg(float p, float d, float i)
        {
            this.p = p;
            this.d = d;
            this.i = i;
        }

        public static PIDMsg Deserialize(MessageDeserializer deserializer) => new PIDMsg(deserializer);

        private PIDMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.p);
            deserializer.Read(out this.d);
            deserializer.Read(out this.i);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.p);
            serializer.Write(this.d);
            serializer.Write(this.i);
        }

        public override string ToString()
        {
            return "PIDMsg: " +
            "\np: " + p.ToString() +
            "\nd: " + d.ToString() +
            "\ni: " + i.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
