//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class PointArrayMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/PointArray";
        public override string RosMessageName => k_RosMessageName;

        public PointMsg lf;
        public PointMsg rf;
        public PointMsg lh;
        public PointMsg rh;

        public PointArrayMsg()
        {
            this.lf = new PointMsg();
            this.rf = new PointMsg();
            this.lh = new PointMsg();
            this.rh = new PointMsg();
        }

        public PointArrayMsg(PointMsg lf, PointMsg rf, PointMsg lh, PointMsg rh)
        {
            this.lf = lf;
            this.rf = rf;
            this.lh = lh;
            this.rh = rh;
        }

        public static PointArrayMsg Deserialize(MessageDeserializer deserializer) => new PointArrayMsg(deserializer);

        private PointArrayMsg(MessageDeserializer deserializer)
        {
            this.lf = PointMsg.Deserialize(deserializer);
            this.rf = PointMsg.Deserialize(deserializer);
            this.lh = PointMsg.Deserialize(deserializer);
            this.rh = PointMsg.Deserialize(deserializer);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.lf);
            serializer.Write(this.rf);
            serializer.Write(this.lh);
            serializer.Write(this.rh);
        }

        public override string ToString()
        {
            return "PointArrayMsg: " +
            "\nlf: " + lf.ToString() +
            "\nrf: " + rf.ToString() +
            "\nlh: " + lh.ToString() +
            "\nrh: " + rh.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
