//Do not edit! This file was generated by Unity-ROS MessageGeneration.
using System;
using System.Linq;
using System.Collections.Generic;
using System.Text;
using Unity.Robotics.ROSTCPConnector.MessageGeneration;

namespace RosMessageTypes.Champ
{
    [Serializable]
    public class VelocitiesMsg : Message
    {
        public const string k_RosMessageName = "champ_msgs/Velocities";
        public override string RosMessageName => k_RosMessageName;

        public float linear_x;
        public float linear_y;
        public float angular_z;

        public VelocitiesMsg()
        {
            this.linear_x = 0.0f;
            this.linear_y = 0.0f;
            this.angular_z = 0.0f;
        }

        public VelocitiesMsg(float linear_x, float linear_y, float angular_z)
        {
            this.linear_x = linear_x;
            this.linear_y = linear_y;
            this.angular_z = angular_z;
        }

        public static VelocitiesMsg Deserialize(MessageDeserializer deserializer) => new VelocitiesMsg(deserializer);

        private VelocitiesMsg(MessageDeserializer deserializer)
        {
            deserializer.Read(out this.linear_x);
            deserializer.Read(out this.linear_y);
            deserializer.Read(out this.angular_z);
        }

        public override void SerializeTo(MessageSerializer serializer)
        {
            serializer.Write(this.linear_x);
            serializer.Write(this.linear_y);
            serializer.Write(this.angular_z);
        }

        public override string ToString()
        {
            return "VelocitiesMsg: " +
            "\nlinear_x: " + linear_x.ToString() +
            "\nlinear_y: " + linear_y.ToString() +
            "\nangular_z: " + angular_z.ToString();
        }

#if UNITY_EDITOR
        [UnityEditor.InitializeOnLoadMethod]
#else
        [UnityEngine.RuntimeInitializeOnLoadMethod]
#endif
        public static void Register()
        {
            MessageRegistry.Register(k_RosMessageName, Deserialize);
        }
    }
}
